#pragma config(Motor,  motorA,          button,        tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          button2,       tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

int mode = 1;

	while(true)
	{
		if (mode == 1)
		{
			while (SensorValue(button) == 0&&SensorValue(button2) == 0)
			{
				motor[motorA] = 40;
				motor[motorB] = 50;
			}
			motor[motorA] = -15;
			motor[motorB] = -50;
			wait1Msec(1000);
		}
	}

if (mode == 2)
{
	int speed;

	while (true)
	{
		motor[motorA] = 100;
		motor[motorB] = speed;

		speed = 1;

	}
}

		int speed;

	while (speed>100)
	{

		motor[motorA] = 100;
		motor[motorB] = speed;
		wait1Msec(50);

		speed = speed + 1;
	}

	motor[motorA] = 100;
	motor[motorB] = 100;
	wait1Msec(5000);


}
